const INVALID_CREDENTIALS = 'INVALID_CRENDENTIALS'
const INVALID_EMAIL = 'INVALID_EMAIL'
const INVALID_PHONE = 'INVALID_PHONE'
const INVALID_CNPJ = 'INVALID_CNPJ'
const INVALID_PASSWORD = 'INVALID_PASSWORD'
const INVALID_NAME = 'INVALID_NAME'

export {
  INVALID_CREDENTIALS,
  INVALID_PHONE,
  INVALID_EMAIL,
  INVALID_CNPJ,
  INVALID_NAME,
  INVALID_PASSWORD
}
